### ISSUE TITLE
error 1142

### ISSUE THREAD

**Issue by gudumibug** [burpheart/NexusPHP_safe#2]
Error:SELECT command denied to user 'gudumibug'@'localhost' for table 'uc_vars'
Errno:1142
SQL::SELECT value FROM `ucenter`.uc_vars WHERE name='noteexists1'

**Comment by burpheart** [comment]
用户没有uc_vars表的操作权限 用数据库root账号授权一下

**Comment by gudumibug** [comment]
大佬 貌似没这个表  宝塔

**Comment by burpheart** [comment]
安装方法 https://bbs.itzmx.com/thread-2227-1-1.html
